apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: webserver
  template:
    metadata:
      labels:
        tier: webserver
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
